# Site settings
title: Mohsen Ahmadi, PM, PSMI
description: >- # this means to ignore newlines until "baseurl:"
  Agile Product Manager, Python Lover, Scrum Master, Coffee Addiction, Project Manager, Have a Big Dream, Workout, Nutella, Workout, Travel. Agile Coach, Startup's Mentor
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ahmadi.pm" # the base hostname & protocol for your site, e.g. http://example.com
repository: mohsenahmadi/mohsenahmadi.github.io

# Build settings
markdown: kramdown
remote_theme: YoussefRaafatNasry/portfolYOU

# Author Info
author:
  name     : Mohsen Ahmadi
  image    : https://ahmadi.pm/assets/profile.jpg
  github   : mohsenahmadi
  twitter  : usdimo
  linkedin : mohsenahmadii
  facebook : mohsenahmadii

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name

# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

# Posts default Permalink
permalink: articles/:title

url: "https://ahmadi.space" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
